variables:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCOUNT_ID: "058264373862"
  ECR_REPO_URL: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_PROJECT_NAME}-${CI_ENVIRONMENT_NAME}
  DOCKER_IMAGE: ${ECR_REPO_URL}:${CI_COMMIT_SHORT_SHA}

stages:
  - build
  - test

# build-and-push:
#   stage: build
#   image: 
#     name: amazon/aws-cli:latest
#     entrypoint: [""]
#   services:
#     - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""
#   before_script:
#     # Configure AWS credentials
#     - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
#     - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
#     - aws configure set region ${AWS_DEFAULT_REGION}
#     # Install Docker
#     - amazon-linux-extras install docker
#     - aws --version
#     - docker --version
#     # Login to ECR
#     - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPO_URL}
#   script:
#     # Build and push Docker image
#     - cd modules/poc-api/src
#     - docker build -t ${DOCKER_IMAGE} .
#     - docker push ${DOCKER_IMAGE}
#     # Tag as latest
#     - docker tag ${DOCKER_IMAGE} ${ECR_REPO_URL}:latest
#     - docker push ${ECR_REPO_URL}:latest
#   environment:
#     name: dev
#   # rules:
#   #   - if: $CI_COMMIT_BRANCH == "main"
#   #     changes:
#   #       - modules/poc-api/src/**/* 

test-terraform:
  stage: test
  image: 
    name: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y wget unzip curl
    - wget https://releases.hashicorp.com/terraform/1.10.0/terraform_1.10.0_linux_amd64.zip
    - unzip terraform_1.10.0_linux_amd64.zip
    - mv terraform /usr/local/bin
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    # Configure AWS credentials
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set region ${AWS_DEFAULT_REGION}
  script:
    - aws --version
    - terraform --version